# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Loris01100.CmdBoard
PackageVersion: 0.2.0
PackageLocale: en-US
Publisher: Loris01100
Author: Loris01100
PublisherUrl: https://github.com/Loris01100
PublisherSupportUrl: https://github.com/Loris01100/CmdBoard/issues
PackageName: CmdBoard
PackageUrl: https://github.com/Loris01100/CmdBoard
License: MIT
LicenseUrl: https://github.com/Loris01100/CmdBoard/blob/main/LICENSE
ShortDescription: Terminal dashboard to launch apps and track play time, with XP and rewards
Moniker: cmdboard
Tags:
- dashboard
- launcher
- terminal
- tui
- gaming
ReleaseNotesUrl: https://github.com/Loris01100/CmdBoard/releases/tag/v0.2.0
ManifestType: defaultLocale
ManifestVersion: 1.10.0
