# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Loris01100.CmdBoard
PackageVersion: 0.2.0
InstallerType: wix
Scope: machine
UpgradeBehavior: install
Commands:
- cmdboard
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Loris01100/CmdBoard/releases/download/v0.2.0/cmdboard-x86_64-pc-windows-msvc.msi
  InstallerSha256: 040BBFF591D10068972358651269B31C8624A2BC0A519B7FB9007E901B4E1941
  ProductCode: '{76A011CD-FEC1-407D-91F6-128AAEC43E53}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{94256D30-D74C-400B-8D07-B858839C666B}'
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-10-07
